version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      # - CHOKIDAR_USEPOLLING=true
    ports:
      - 5000:5000
    volumes:
      - ./:/server
    command: npm run start:dev
